Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2024-08, with the labels that each got.

#671 [BUGFIX] Fix comment parsing to support multiple comments (backported)
  CHANGELOG.md
  src/Rule/Rule.php
  tests/ParserTest.php
Labels: bug

#672 [BUGFIX] Fix comment parsing to support multiple comments
  CHANGELOG.md
  src/Rule/Rule.php
  tests/ParserTest.php
Labels: bug

#666 [TASK] Avoid Hungarian notation in a testcase
  tests/Comment/CommentTest.php
Labels: cleanup

#667 [TASK] Fix typos in comments and names and improve some comments
  src/CSSList/CSSList.php
  src/Value/Value.php
  tests/CSSList/AtRuleBlockListTest.php
  tests/CSSList/DocumentTest.php
  tests/ParserTest.php
Labels: cleanup

#675 [FEATURE] Add PHP 8.4 to the CI matrix
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: backport

#664 [BUGFIX] Fix type errors in PHP strict mode
  CHANGELOG.md
  src/Value/Size.php
  tests/ParserTest.php
Labels: bug, cleanup

#678 [TASK] Avoid Hungarian notation in a testcase
  tests/RuleSet/DeclarationBlockTest.php
Labels: cleanup

#662 [TASK] Document the general contribution workflow
  .github/CONTRIBUTING.md
Labels: documentation, blocked

#686 [TASK] Be less strict about the `@covers` annotation
  phpunit.xml
Labels: to-backport

#690 [TASK] Avoid Hungarian notation in a testcase
  tests/OutputFormatTest.php
Labels: cleanup

#692 [TASK] Block installations on unsupported higher PHP versions
  CHANGELOG.md
  composer.json
Labels: backport

#694 [BUGFIX] Fix the image URL of the CI status badge
  README.md
Labels: documentation, bug

#695 [BUGFIX] Fix type errors in PHP strict mode
  CHANGELOG.md
  src/Value/Size.php
  tests/ParserTest.php
Labels: bug

#689 [TASK] Improve formatting in the changelog
  CHANGELOG.md
Labels: documentation, cleanup, to-backport

#682 [TASK] Also allow higher versions of PHPUnit
  composer.json
Labels: dependencies
