Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2024-02, with the labels that each got.

#429 [BUGFIX] Git-ignore the PHPUnit result cache
  .gitignore
Labels: bug

#435 [TASK] Make the testcases final
  tests/CSSList/AtRuleBlockListTest.php
  tests/CSSList/DocumentTest.php
  tests/CSSList/KeyFrameTest.php
  tests/Comment/CommentTest.php
  tests/OutputFormatTest.php
  tests/ParserTest.php
  tests/RuleSet/DeclarationBlockTest.php
  tests/RuleSet/LenientParsingTest.php
  tests/Value/CalcRuleValueListTest.php
Labels: cleanup

#440 [CLEANUP] Autoformat the code
  src/OutputFormatter.php
  src/Value/Value.php
  tests/Comment/CommentTest.php
Labels: cleanup

#441 [TASK] Add some Composer settings
  composer.json
Labels: cleanup

#437 [BUGFIX] Avoid double CI runs for pull requests
  .github/workflows/ci.yml
Labels: bug

#445 [BUGFIX] Use the Composer-installed PHPStan for creating the baseline
  composer.json
Labels: bug

#448 [BUGFIX] Prevent accessing an uninitialized variable in `DeclarationB…
  config/phpstan-baseline.neon
  src/RuleSet/DeclarationBlock.php
Labels: bug

#449 [FEATURE] Add unit tests for the existing `Settings` methods
  CHANGELOG.md
  tests/SettingsTest.php
Labels: enhancement

#470 [TASK] Add visibility to all class/interface constants
  CHANGELOG.md
  src/Parsing/ParserState.php
  src/Property/AtRule.php
  src/Property/KeyframeSelector.php
  src/Property/Selector.php
  src/Value/CalcFunction.php
  src/Value/Size.php
  tests/OutputFormatTest.php
Labels: cleanup

#456 [BUGFIX] Allow at-rules to be parsed in strict mode
  CHANGELOG.md
  src/CSSList/CSSList.php
  tests/CSSList/AtRuleBlockListTest.php
Labels: bug

#475 [BUGFIX] Allow at-rules to be parsed in strict mode (#456)
  CHANGELOG.md
  src/CSSList/CSSList.php
  tests/CSSList/AtRuleBlockListTest.php
Labels: bug

#478 [TASK] Prepare the 8.5.1 release
  CHANGELOG.md
  composer.json
Labels: documentation

#415 [FEATURE] Add support for the `dvh`, `lvh` and `svh` length units
  CHANGELOG.md
  src/Value/Size.php
  tests/Value/SizeTest.php
Labels: enhancement

#484 [BUGFIX] Invoke PHIVE-installed tools via shell
  .phive/phars.xml
  composer.json
Labels: bug, developer-specific

#485 [BUGFIX] Handle incorrect RGB colors better
  CHANGELOG.md
  src/Value/Color.php
  tests/ParserTest.php
  tests/fixtures/colortest.css
Labels: bug

#488 [FEATURE] Add Composer scripts to run unit tests
  README.md
Labels: documentation, enhancement, developer-specific

#491 [DOCS] Fix typo in the changelog
  CHANGELOG.md
Labels: documentation

#490 [BUGFIX] Handle incorrect RGB colors better (#485)
  CHANGELOG.md
  src/Value/Color.php
  tests/ParserTest.php
  tests/fixtures/colortest.css
Labels: bug

#500 [TASK] Mark all class constants as `@internal`
  CHANGELOG.md
  src/Parsing/ParserState.php
  src/Property/AtRule.php
  src/Property/KeyframeSelector.php
  src/Property/Selector.php
  src/Value/CalcFunction.php
  src/Value/Size.php
Labels: documentation

#413 [TASK] Avoid poor scaling of `array_search()` with very long arrays
  CHANGELOG.md
  src/Value/Value.php
Labels: enhancement, optimization

#505 [TASK] Reorder things in the class diagram source code
  README.md
Labels: documentation

#509 [DOCS] Correct typo in class diagram ("abstruct" -> "abstract")
  README.md
Labels: documentation

#508 [DOCS] Remove trailing whitespace in README.md
  README.md
Labels: documentation, cleanup
