Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2024-07, with the labels that each got.

#630 [TASK] Prepare the 8.6.0 release
  CHANGELOG.md
Labels: release

#632 [TASK] Prefix native function calls with a backslash
  bin/quickdump.php
  src/CSSList/CSSBlockList.php
  src/CSSList/CSSList.php
  src/CSSList/Document.php
  src/OutputFormat.php
  src/OutputFormatter.php
  src/Parsing/ParserState.php
  src/Parsing/UnexpectedTokenException.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Property/Selector.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Settings.php
  src/Value/CSSString.php
  src/Value/CalcFunction.php
  src/Value/Color.php
  src/Value/Size.php
  src/Value/Value.php
  src/Value/ValueList.php
  tests/ParserTest.php
  tests/RuleSet/DeclarationBlockTest.php
  tests/RuleSet/LenientParsingTest.php
  tests/SettingsTest.php
Labels: cleanup, optimization

#633 [CLEANUP] Remove unused imports
  config/rector.php
  src/Parsing/ParserState.php
  src/Value/Value.php
Labels: cleanup

#637 [TASK] Drop surplus empty lines from PHPDoc
  src/CSSList/Document.php
  src/OutputFormatter.php
Labels: cleanup

#638 [CLEANUP] Sort the types in union type PHPDoc annotations
  src/CSSList/CSSList.php
Labels: cleanup

#639 [CLEANUP] Always escape backslashes in strings
  src/Parsing/ParserState.php
  src/Property/KeyframeSelector.php
  src/Property/Selector.php
  src/Value/CSSString.php
  src/Value/Size.php
  src/Value/Value.php
  tests/ParserTest.php
Labels: cleanup

#631 [TASK] Add more PHP-CS-Fixer rules
  config/php-cs-fixer.php
Labels: cleanup

#642 [CLEANUP] Use single-quoted string literals whenever possible
  config/php-cs-fixer.php
  src/CSSList/CSSList.php
  src/OutputFormat.php
  src/Parsing/ParserState.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSString.php
  src/Value/Size.php
  src/Value/Value.php
  tests/OutputFormatTest.php
  tests/ParserTest.php
  tests/RuleSet/LenientParsingTest.php
Labels: cleanup

#643 [TASK] Ensure PHP 8.4 compatibility for nullable parameters
  config/php-cs-fixer.php
  src/CSSList/Document.php
  src/Parser.php
  src/RuleSet/RuleSet.php
Labels: bug, cleanup

#645 [CLEANUP] Move the `nullable_type_declaration` rule
  config/php-cs-fixer.php
Labels: cleanup

#649 [TASK] Use the new contact email address in the code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#652 [TASK] Update the code of conduct to version 2.1
  CODE_OF_CONDUCT.md
Labels: documentation
