Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2024-06, with the labels that each got.

#547 [CLEANUP] Fix indentation of dependabot configuration
  .github/dependabot.yml
Labels: cleanup

#548 [CLEANUP] Fix indentation of GHA configuration
  .github/workflows/ci.yml
  .github/workflows/codecoverage.yml
Labels: cleanup

#552 [CLEANUP] rector: Changes unneeded null check to ?? operator
  src/RuleSet/DeclarationBlock.php
  src/Value/Size.php
Labels: cleanup

#555 [CLEANUP] rector: Add void to PHPUnit test methods
  tests/CSSList/AtRuleBlockListTest.php
  tests/CSSList/DocumentTest.php
  tests/CSSList/KeyFrameTest.php
  tests/Comment/CommentTest.php
  tests/OutputFormatTest.php
  tests/ParserTest.php
  tests/RuleSet/DeclarationBlockTest.php
  tests/RuleSet/LenientParsingTest.php
  tests/Value/CalcRuleValueListTest.php
Labels: cleanup

#553 [CLEANUP] rector: Long array to short array and Change list() to array destruct
  src/RuleSet/DeclarationBlock.php
Labels: cleanup

#565 [TASK] Move linting to a Composer script and use it on CI
  .github/workflows/ci.yml
  composer.json
Labels: enhancement

#561 [TASK] Remove `Document::getAllSelectors`
  CHANGELOG.md
  src/CSSList/Document.php
Labels: removal

#562 [TASK] Remove `Rule::setValues`
  CHANGELOG.md
  src/Rule/Rule.php
Labels: removal

#582 [TASK] Remove `Rule::getValues`
  CHANGELOG.md
  src/Rule/Rule.php
  tests/ParserTest.php
Labels: removal

#583 [TASK] Add kudos to @ziegenberg to the changelog
  CHANGELOG.md
  README.md
Labels: documentation

#566 [TASK] Deprecate `Document::expandShorthands`
  CHANGELOG.md
  src/CSSList/Document.php
Labels: deprecation

#581 [CLEANUP] Rector: Add strict return type based on returned strict expr type
  src/CSSList/AtRuleBlockList.php
  src/CSSList/Document.php
  src/CSSList/KeyFrame.php
  src/Parsing/ParserState.php
  src/RuleSet/DeclarationBlock.php
  src/Value/Size.php
Labels: cleanup

#586 [CLEANUP] Rector: Change numeric return type based on strict returns type operations
  src/Parsing/ParserState.php
Labels: cleanup

#587 [CLEANUP] Rector: Change return type based on strict returns type operations
  src/Parsing/ParserState.php
Labels: cleanup

#588 [CLEANUP] Rector: Add method return type based on strict ternary values
  src/CSSList/CSSList.php
  src/Parsing/ParserState.php
Labels: cleanup

#589 [CLEANUP] Rector: Change return type based on strict scalar returns -…
  src/CSSList/AtRuleBlockList.php
  src/CSSList/Document.php
  src/CSSList/KeyFrame.php
  src/Comment/Comment.php
  src/OutputFormatter.php
  src/Parsing/ParserState.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/Value/CSSString.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/Value.php
Labels: cleanup

#590 [CLEANUP] Rector: Add return type from return direct array
  src/Parsing/ParserState.php
  src/Rule/Rule.php
  tests/CSSList/DocumentTest.php
  tests/RuleSet/DeclarationBlockTest.php
Labels: cleanup

#591 [CLEANUP] Rector: Add return type to function like with return new
  src/CSSList/Document.php
  src/OutputFormat.php
  src/Parsing/ParserState.php
  src/Rule/Rule.php
  src/Settings.php
  src/Value/CSSString.php
  src/Value/CalcFunction.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/Value.php
Labels: cleanup

#593 [BUGFIX] Fix undefined local variable in `CalcFunction::parse()`
  CHANGELOG.md
  config/phpstan-baseline.neon
  src/Value/CalcFunction.php
Labels: bug

#545 [FEATURE] Add support for inserting an item in a CSSList
  CHANGELOG.md
  src/CSSList/CSSList.php
  tests/CSSList/DocumentTest.php
Labels: enhancement

#597 [CLEANUP] Rector: Add return type void to function like without any return
  src/CSSList/CSSList.php
  src/CSSList/Document.php
  src/CSSList/KeyFrame.php
  src/Comment/Comment.php
  src/OutputFormat.php
  src/Parser.php
  src/Parsing/Anchor.php
  src/Parsing/ParserState.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Property/Selector.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/Color.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/ValueList.php
  tests/CSSList/DocumentTest.php
  tests/ParserTest.php
Labels: cleanup

#600 [CLEANUP] Rector: Adds param type declaration based on PHPUnit provider return type declaration
  tests/CSSList/AtRuleBlockListTest.php
  tests/RuleSet/DeclarationBlockTest.php
Labels: cleanup

#602 [CLEANUP] Rector: Add strict return type based native function or class method return
  src/OutputFormatter.php
Labels: cleanup

#603 [CLEANUP] Rector: Add strict return type based native function or class method return
  src/OutputFormatter.php
  src/Parser.php
  src/Parsing/ParserState.php
  tests/ParserTest.php
Labels: cleanup

#592 [TASK] Update PHP-CS-Fixer
  .phive/phars.xml
  config/php-cs-fixer.php
Labels: dependencies

#608 [CLEANUP] Add native return types to `parse()`
  src/Value/CSSFunction.php
  src/Value/CalcFunction.php
  src/Value/Color.php
Labels: cleanup

#609 [CLEANUP] Ensure all tests actually have an assertion
  tests/RuleSet/LenientParsingTest.php
Labels: cleanup

#595 [TASK] Use proper code formatting in the README
  README.md
Labels: documentation

#599 [CLEANUP] Extract CSSFunction methods parseName and parseArguments
  src/Value/CSSFunction.php
  src/Value/CalcFunction.php
  src/Value/Color.php
Labels: cleanup, refactor

#610 [BUGFIX] Support Lint on Windows
  composer.json
Labels: bug, developer-specific

#607 [FEATURE] Support arithmetic operators in CSS functions
  CHANGELOG.md
  src/Value/Value.php
  tests/Value/ValueTest.php
Labels: enhancement

#614 [CLEANUP] Simplify calls to Composer scripts from Composer scripts
  composer.json
Labels: cleanup

#617 [BUGFIX] Fix undefined local variable in `CalcFunction::parse()`
  CHANGELOG.md
  config/phpstan-baseline.neon
  src/Value/CalcFunction.php
Labels: bug

#606 [CLEANUP] Rector: Add missing return type declaration based on parent class method
  src/CSSList/AtRuleBlockList.php
  src/CSSList/CSSList.php
  src/CSSList/KeyFrame.php
  src/Comment/Comment.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Property/Selector.php
  src/Rule/Rule.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/ValueList.php
Labels: cleanup

#618 [BUGFIX] Provide the usual set of delimiters in parseValue tests
  tests/Value/ValueTest.php
Labels: bug, cleanup, enhancement, testing, developer-specific

#620 [TASK] Test parsing arithmetic operators in clamp function
  tests/Value/ValueTest.php
Labels: testing

#626 [CLEANUP] Add missing PR number to changelog
  CHANGELOG.md
Labels: cleanup

#623 [FEATURE] Add support for inserting an item in a CSSList (#545)
  CHANGELOG.md
  src/CSSList/CSSList.php
  tests/CSSList/DocumentTest.php
Labels: enhancement, backport

#627 [FEATURE] Add support for the `dvh`, `lvh` and `svh` length units (#415)
  CHANGELOG.md
  src/Value/Size.php
  tests/Value/SizeTest.php
Labels: enhancement, backport

#628 [TASK] Avoid poor scaling of array_search() with very long arrays (#413)
  CHANGELOG.md
  src/Value/Value.php
Labels: enhancement, optimization, backport

#584 [TASK] Always use the strict version of `in_array` & friends
  config/php-cs-fixer.php
  src/Parsing/ParserState.php
  src/RuleSet/DeclarationBlock.php
  src/Value/CalcFunction.php
Labels: cleanup

#616 [TASK] Start the contributor guidelines with the CoC
  .gitattributes
  .github/CONTRIBUTING.md
  CODE_OF_CONDUCT.md
Labels: documentation, developer-specific

#624 [FEATURE] Support arithmetic operators in CSS functions (#607)
  CHANGELOG.md
  src/Value/Value.php
  tests/Value/ValueTest.php
Labels: enhancement, backport
