Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2024-03, with the labels that each got.

#507 [CLEANUP] Use common ancestor `Value` in type specifications
  README.md
  src/Value/CSSFunction.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/Value.php
  src/Value/ValueList.php
Labels: cleanup

#513 [CLEANUP] Move some things in the class diagram code around
  README.md
Labels: documentation, cleanup

#515 [TASK] Use a generated class/diagram list in the class diagram
  README.md
Labels: documentation

#517 [TASK] Fix typo "abstruct" in the class diagram (again)
  README.md
Labels: documentation

#518 [TASK] Use auto-generated hierarchy in class diagram
  README.md
Labels: documentation
