Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2024-10, with the labels that each got.

#731 Mark Exception Classes as Final
  src/Parsing/OutputException.php
  src/Parsing/UnexpectedEOFException.php
Labels: hacktoberfest

#730 Add GitHub Action to Require Tests in Pull Requests
  .github/workflows/require-tests.yml
Labels: hacktoberfest, enhancement, hacktoberfest-accepted

#738 [TASK] Add some more tests for parsing comments
  tests/RuleSet/DeclarationBlockTest.php
Labels: to-backport

#740 [BUGFIX] Revert broken support for multiple comments
  CHANGELOG.md
  src/Rule/Rule.php
  tests/ParserTest.php
  tests/RuleSet/DeclarationBlockTest.php
Labels: bug, to-backport

#746 [BUGFIX] Avoid implicit nullable parameters
  CHANGELOG.md
  src/CSSList/AtRuleBlockList.php
  src/CSSList/Document.php
  src/CSSList/KeyFrame.php
  src/Comment/Comment.php
  src/Parser.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Renderable.php
  src/Rule/Rule.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/CalcRuleValueList.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/ValueList.php
Labels: bug

#744 [TASK] Configure PHPUnit to be more strict
  phpunit.xml
Labels: backport

#750 [CLEANUP] Autoformat the changelog
  CHANGELOG.md
Labels: documentation, cleanup, backport

#751 [BUGFIX] Fix another implictly nullable parameter
  CHANGELOG.md
  src/RuleSet/RuleSet.php
Labels: bug, backport

#752 [DOCS] Explain code reviews in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation, developer-specific

#742 [TASK] Prepare the 8.7.0 release
  CHANGELOG.md
Labels: release

#753 [DOCS] Add a section on development deps to `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation, developer-specific

#748 [CLEANUP] Autoformat the code
  src/Parsing/ParserState.php
  src/Value/Size.php
  tests/CSSList/AtRuleBlockListTest.php
  tests/ParserTest.php
  tests/Value/SizeTest.php
Labels: cleanup, to-backport

#749 [CLEANUP] Autoformat the code
  src/Value/Size.php
  tests/CSSList/AtRuleBlockListTest.php
  tests/Value/SizeTest.php
Labels: cleanup, backport
