Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2025-03, with the labels that each got.

#1040 [TASK] Mark `Selector::isValid()` as `@internal`
  CHANGELOG.md
  src/Property/Selector.php
Labels: backport

#1017 [TASK] Make `Selector` a `Renderable`
  CHANGELOG.md
  src/Property/Selector.php
  tests/Functional/Property/SelectorTest.php
  tests/Unit/Property/SelectorTest.php
Labels: cleanup, enhancement

#1044 [TASK] Add more native type declarations for `Selector`
  CHANGELOG.md
  src/Property/Selector.php
Labels: cleanup

#1049 [FEATURE] Add a utility class to calculate selector specificity
  src/Property/Selector/SpecificityCalculator.php
  tests/Unit/Property/Selector/SpecificityCalculatorTest.php
Labels: enhancement

#1050 [CLEANUP] Refactor `CSSBlockList::getAllRuleSets()`
  src/CSSList/CSSBlockList.php
Labels: cleanup

#1039 [CLEANUP] Improve some variable names in `RuleSet`
  src/RuleSet/RuleSet.php
Labels: cleanup

#1051 [BUGFIX] Fix a type annotation in `RuleSet`
  config/phpstan-baseline.neon
  src/RuleSet/RuleSet.php
Labels: bug, cleanup

#1054 [CLEANUP] Simplify a data provider
  tests/Unit/Value/ValueTest.php
Labels: cleanup

#1055 [CLEANUP] Make a type annotation in a test more specific
  tests/Unit/Value/ValueTest.php
Labels: cleanup

#1012 [TASK] Deprecate `__toString()`
  CHANGELOG.md
  src/CSSList/AtRuleBlockList.php
  src/CSSList/CSSList.php
  src/CSSList/KeyFrame.php
  src/Comment/Comment.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Property/Selector.php
  src/Renderable.php
  src/Rule/Rule.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/ValueList.php
Labels: backport

#1056 [TASK] Avoid the deprecated `__toString()` in `ParserTest`
  tests/ParserTest.php
Labels: cleanup

#1059 [BUGFIX] Render rules in line and column number order
  CHANGELOG.md
  src/RuleSet/RuleSet.php
  tests/Functional/RuleSet/DeclarationBlockTest.php
Labels: bug

#894 [TASK] Deprecate method forwarding `OutputFormat` to `OutputFormatter`
  CHANGELOG.md
  src/OutputFormat.php
Labels: to-backport

#1060 [TASK] Deprecate method forwarding `OutputFormat` to `OutputFormatter`
  CHANGELOG.md
  src/OutputFormat.php
Labels: backport

#1061 [BUGFIX] Fix a type annotation in `RuleSet`
  src/RuleSet/RuleSet.php
Labels: bug, cleanup, backport

#1063 [CLEANUP] Avoid Hungarian notation for `value`
  src/Value/Value.php
Labels: cleanup

#1064 [CLEANUP] Avoid Hungarian notation for `*stack*`
  src/Value/Value.php
Labels: cleanup

#1065 Allow rules to be in any order in shorthand tests
  tests/ParserTest.php
  tests/RuleSet/DeclarationBlockTest.php
Labels: cleanup, testing

#1066 [CLEANUP] Avoid Hungarian notation for `arguments`
  src/OutputFormat.php
  src/Value/CSSFunction.php
  src/Value/Value.php
Labels: cleanup

#1067 [CLEANUP] Avoid Hungarian notation for `*delimiter*`
  src/Value/Value.php
Labels: cleanup

#1070 [CLEANUP] Avoid Hungarian notation for `function`
  src/Value/CalcFunction.php
  src/Value/Value.php
Labels: cleanup

#1069 [CLEANUP] Avoid Hungarian notation in `Value`
  src/Value/Value.php
Labels: cleanup

#896 [TASK] Mark `OutputFormatter` as `@internal`
  CHANGELOG.md
  src/OutputFormat.php
  src/OutputFormatter.php
Labels: to-backport

#1072 [CLEANUP] Avoid Hungarian notation for `calcRuleValueList`
  src/Value/CalcFunction.php
Labels: cleanup

#1073 [TASK] Mark `OutputFormatter` as `@internal`
  CHANGELOG.md
  src/OutputFormat.php
  src/OutputFormatter.php
Labels: backport

#1074 [CLEANUP] Avoid Hungarian notation for `components`
  src/Value/CSSFunction.php
  src/Value/CalcRuleValueList.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/ValueList.php
Labels: cleanup

#1075 [CLEANUP] Avoid Hungarian notation for `lastComponentType`
  src/Value/CalcFunction.php
Labels: cleanup

#1077 [CLEANUP] Avoid Hungarian notation for `value`
  src/OutputFormat.php
  src/Parsing/ParserState.php
  src/Rule/Rule.php
  src/Value/CalcFunction.php
Labels: cleanup

#1080 [CLEANUP] Avoid Hungarian notation for `begin`
  src/Value/CSSString.php
Labels: cleanup

#1081 [CLEANUP] Avoid Hungarian notation for `quote` (#1080)
  src/Value/CSSString.php
Labels: cleanup

#1084 [TASK] Extract value parsing functional tests (part 1)
  tests/Functional/Value/ValueTest.php
Labels: testing

#1085 [CLEANUP] Avoid Hungarian notation for `size`
  src/Value/Size.php
Labels: cleanup

#1088 [CLEANUP] Avoid Hungarian notation for `unit` and `sizeUnits`
  src/Value/Size.php
Labels: cleanup

#1090 [CLEANUP] Avoid Hungarian notation for `isColorComponent`
  src/Value/Size.php
Labels: cleanup

#1092 [CLEANUP] Avoid Hungarian notation in `Size::render()`
  src/Value/Size.php
Labels: cleanup

#1093 [CLEANUP] Avoid Hungarian notation for `url`
  src/Value/URL.php
Labels: cleanup

#1089 [CLEANUP] Avoid Hungarian notation for `tokenLength`
  src/Value/Size.php
Labels: cleanup

#1094 [CLEANUP] Avoid Hungarian notation for `character`
  src/Value/URL.php
Labels: cleanup

#1095 [CLEANUP] Avoid Hungarian notation for `sizeUnit`
  src/Value/Size.php
Labels: cleanup

#1096 [CLEANUP] Avoid Hungarian notation for `useUrl`
  src/Value/URL.php
Labels: cleanup

#1097 [CLEANUP] Avoid Hungarian notation in `OutputFormatter`
  src/OutputFormatter.php
Labels: cleanup

#1098 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 1)
  src/OutputFormat.php
Labels: cleanup

#1099 [CLEANUP] Improve some `OutputFormat` property and getter names
  src/OutputFormat.php
  src/OutputFormatter.php
  src/Value/Color.php
  tests/Unit/OutputFormatTest.php
Labels: cleanup

#1101 [CLEANUP] Avoid Hungarian notation in the tests
  tests/Comment/CommentTest.php
  tests/ParserTest.php
  tests/RuleSet/DeclarationBlockTest.php
Labels: cleanup

#1102 [CLEANUP] Avoid Hungarian notation in `SpecificityCalculator`
  src/Property/Selector/SpecificityCalculator.php
Labels: cleanup

#1104 [CLEANUP] Avoid Hungarian notation in `CSSBlockList`
  src/CSSList/CSSBlockList.php
Labels: cleanup

#1105 [CLEANUP] Avoid Hungarian notation in `DeclarationBlock`
  src/RuleSet/DeclarationBlock.php
Labels: cleanup

#1106 [CLEANUP] Use the explicit `OutputFormat` setters in the tests
  config/phpstan-baseline.neon
  tests/OutputFormatTest.php
Labels: cleanup

#1109 [CLEANUP] Avoid Hungarian notation in comments
  src/RuleSet/RuleSet.php
Labels: cleanup

#1100 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 2)
  src/OutputFormat.php
Labels: cleanup

#1111 [CLEANUP] Avoid Hungarian notation in `Size`
  src/Value/Size.php
Labels: cleanup

#1112 [CLEANUP] Avoid Hungarian notation for `numberOfLines`
  src/Parsing/ParserState.php
Labels: cleanup

#1113 [CLEANUP] Avoid Hungarian notation for `matches`
  src/Parsing/ParserState.php
Labels: cleanup

#1114 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 3)
  src/OutputFormat.php
Labels: cleanup

#1115 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 4)
  src/CSSList/AtRuleBlockList.php
  src/OutputFormat.php
  tests/Unit/OutputFormatTest.php
Labels: cleanup

#1116 [CLEANUP] Avoid Hungarian notation for `input`
  src/Parsing/ParserState.php
Labels: cleanup

#1117 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 5)
  src/OutputFormat.php
Labels: cleanup

#1118 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 6)
  src/OutputFormat.php
Labels: cleanup

#1119 [CLEANUP] Avoid Hungarian notation for `expression`
  src/Parsing/ParserState.php
Labels: cleanup

#1120 [CLEANUP] Avoid Hungarian notation for `peek`
  src/Parsing/ParserState.php
Labels: cleanup

#1121 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 7)
  src/OutputFormat.php
  src/RuleSet/DeclarationBlock.php
  tests/Unit/OutputFormatTest.php
Labels: cleanup

#1122 [CLEANUP] Avoid Hungarian notation for `maximumLength`
  src/Parsing/ParserState.php
Labels: cleanup

#1123 [CLEANUP] Avoid Hungarian notation for `comment`
  src/Parsing/ParserState.php
Labels: cleanup

#1124 [CLEANUP] Avoid Hungarian notation for `stopCharacters`
  src/Parsing/ParserState.php
Labels: cleanup

#1125 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 8)
  src/OutputFormat.php
  src/OutputFormatter.php
  tests/Unit/OutputFormatTest.php
Labels: cleanup

#1126 [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 9)
  src/OutputFormat.php
  src/OutputFormatter.php
  tests/Unit/OutputFormatTest.php
Labels: cleanup

#1129 [CLEANUP] Improve some variable names in `ParserState`
  src/Parsing/ParserState.php
Labels: cleanup

#1130 [CLEANUP] Fix some type annotations in `ParserState`
  config/phpstan-baseline.neon
  src/Parsing/ParserState.php
Labels: bug, cleanup

#1132 [BUGFIX] Fix a typo in `indentationLevel`
  src/OutputFormat.php
Labels: bug, cleanup

#1133 [TASK] Mark the `OutputFormat` as not extendable
  CHANGELOG.md
  src/OutputFormat.php
Labels: backport

#1131 [TASK] Mark `OutputFormat` as not extendable
  CHANGELOG.md
  src/OutputFormat.php
Labels: to-backport

#1127 [CLEANUP] Drop empty `OutputFormat` constructor
  src/OutputFormat.php
Labels: cleanup

#1138 [TASK] Add some rendering tests for `Document`
  tests/Functional/CSSList/DocumentTest.php
Labels: testing

#1143 [CLEANUP] Make a type annotation more specific
  src/Property/AtRule.php
Labels: cleanup

#1144 [CLEANUP] Drop an unused internal constant
  src/Property/AtRule.php
Labels: cleanup

#1146 [TASK] Initialize `KeyFrame` properties
  CHANGELOG.md
  config/phpstan-baseline.neon
  src/CSSList/KeyFrame.php
  tests/Unit/CSSList/KeyFrameTest.php
Labels: cleanup

#1148 [CLEANUP] Avoid magic method forwarding in `AtRuleBlockList`
  config/phpstan-baseline.neon
  src/CSSList/AtRuleBlockList.php
Labels: cleanup

#1151 [CLEANUP] Avoid magic method forwarding in `CSSList`
  config/phpstan-baseline.neon
  src/CSSList/CSSList.php
Labels: cleanup

#1152 [CLEANUP] Avoid magic method forwarding in `Color`
  config/phpstan-baseline.neon
  src/Value/Color.php
Labels: cleanup

#1155 [CLEANUP] Avoid magic method forwarding in `Document`
  config/phpstan-baseline.neon
  src/CSSList/Document.php
Labels: cleanup

#1156 [CLEANUP] Avoid magic method forwarding in `Import`
  config/phpstan-baseline.neon
  src/Property/Import.php
Labels: cleanup

#1154 [DOCS] Avoid Hungarian notation in the README
  README.md
Labels: documentation

#1158 [CLEANUP] Avoid magic method forwarding in `KeyFrame`
  config/phpstan-baseline.neon
  src/CSSList/KeyFrame.php
Labels: cleanup

#1159 [CLEANUP] Avoid magic method forwarding in `RuleSet`
  config/phpstan-baseline.neon
  src/RuleSet/RuleSet.php
Labels: cleanup

#1160 [CLEANUP] Avoid magic method forwarding in `Charset`
  config/phpstan-baseline.neon
  src/Property/Charset.php
Labels: cleanup

#1161 [CLEANUP] Avoid magic method forwarding in `DeclarationBlock`
  config/phpstan-baseline.neon
  src/RuleSet/DeclarationBlock.php
Labels: cleanup

#1167 [CLEANUP] Fix method name casing in a call
  config/phpstan-baseline.neon
  src/Value/Color.php
Labels: bug, cleanup

#1169 [BUGFIX] Include comments for all rules in declaration block
  CHANGELOG.md
  src/Rule/Rule.php
  src/RuleSet/RuleSet.php
  tests/ParserTest.php
Labels: bug, to-backport

#1173 [CLEANUP] Clean up `ParserState` a bit
  config/phpstan-baseline.neon
  src/Parsing/ParserState.php
Labels: cleanup

#1174 [BUGFIX] Fix the return type of `Selector::isValid()`
  CHANGELOG.md
  src/Property/Selector.php
  tests/Unit/Property/SelectorTest.php
Labels: bug, cleanup

#1171 [CLEANUP] Make `Commentable` type annotations more specific
  config/phpstan-baseline.neon
  src/CSSList/CSSList.php
  src/Comment/Commentable.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/RuleSet.php
Labels: cleanup

#1180 [TASK] Avoid the deprecated `__toString()` in tests
  tests/Unit/Value/ColorTest.php
  tests/Unit/Value/ValueTest.php
Labels: cleanup

#1182 [BUGFIX] Include comments for all rules in declaration block
  CHANGELOG.md
  src/Rule/Rule.php
  src/RuleSet/RuleSet.php
  tests/ParserTest.php
Labels: bug, backport

#1184 [CLEANUP] Fix type annotation of `::getSelectors()`
  CHANGELOG.md
  config/phpstan-baseline.neon
  src/RuleSet/DeclarationBlock.php
Labels: cleanup

#1199 [CLEANUP] And some more annotations for non-empty strings
  src/CSSList/AtRuleBlockList.php
  src/CSSList/KeyFrame.php
  src/Comment/Comment.php
  src/OutputFormat.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
Labels: cleanup

#1200 [CLEANUP] Make annotations for `OutputFormat` more specific
  src/OutputFormat.php
Labels: cleanup

#1198 [CLEANUP] Improve type annotations in `LineName`
  src/Value/LineName.php
Labels: cleanup

#1209 [CLEANUP] Return `null` from `DeclarationBlock::parse()` on failure
  config/phpstan-baseline.neon
  src/CSSList/CSSList.php
  src/RuleSet/DeclarationBlock.php
  tests/Functional/RuleSet/DeclarationBlockTest.php
Labels: cleanup

#1216 [TASK] Configure the target PHP version for PHPStan
  config/phpstan.neon
Labels: developer-specific

#1206 [TASK] Add trait providing standard implementation of `Commentable`
  composer.json
  src/Comment/CommentContainer.php
  src/Comment/Commentable.php
  tests/Unit/Comment/CommentContainerTest.php
  tests/Unit/Comment/Fixtures/ConcreteCommentContainer.php
Labels: cleanup

#1217 [TASK] Use `CommentContainer` trait to implement `Commentable`
  src/CSSList/CSSList.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/RuleSet.php
Labels: cleanup, refactor

#1219 [TASK] Prevent Dependabot updating "rawr/cross-data-providers"
  .github/dependabot.yml
Labels: dependencies

#1223 [CLEANUP] Move magic deprecation changelog entry to correct section
  CHANGELOG.md
Labels: documentation, cleanup

#1222 [TASK] Integrate changelog entries from 8.8 release
  CHANGELOG.md
Labels: documentation, cleanup

#1224 [TASK] Add to UML diagram that `Selector` implements `Renderable`
  README.md
Labels: documentation

#1221 [TASK] Add `Positionable` interface and implementing trait
  src/Position/Position.php
  src/Position/Positionable.php
  tests/Unit/Position/Fixtures/ConcretePosition.php
  tests/Unit/Position/PositionTest.php
  tests/UnitDeprecated/.gitkeep
  tests/UnitDeprecated/Position/PositionTest.php
Labels: cleanup

#1226 [TASK] Update class diagram to include `CSSListItem`
  README.md
Labels: documentation

#1228 [CLEANUP] Autoformat the code and drop unused imports
  src/CSSList/CSSList.php
  src/Position/Positionable.php
  src/Property/AtRule.php
  src/RuleSet/RuleSet.php
  tests/ParserTest.php
  tests/Unit/Comment/CommentContainerTest.php
Labels: cleanup

#1229 [CLEANUP] Fix typos in test method names
  tests/Unit/Comment/CommentContainerTest.php
Labels: cleanup
