Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2025-02, with the labels that each got.

#859 [FEATURE] Support `none` as color function component value
  CHANGELOG.md
  src/Value/Color.php
  tests/Unit/Value/ColorTest.php
Labels: enhancement, css4

#860 [CLEANUP] Avoid Hungarian notation for `sMediaQuery`
  src/CSSList/CSSList.php
  src/Property/Import.php
Labels: cleanup

#861 [CLEANUP] Avoid Hungarian notation for `bLenientParsing`
  src/CSSList/CSSList.php
  src/Settings.php
Labels: cleanup

#863 [CLEANUP] Avoid Hungarian notation for `sIdentifier`
  src/CSSList/CSSList.php
  src/Value/URL.php
Labels: cleanup

#864 [CLEANUP] Avoid Hungarian notation for `oLocation`
  src/CSSList/CSSList.php
  src/Property/Import.php
Labels: cleanup

#865 [CLEANUP] Avoid Hungarian notation for `oResult`
  src/CSSList/CSSList.php
  src/RuleSet/DeclarationBlock.php
  src/Value/CSSFunction.php
  src/Value/URL.php
Labels: cleanup

#872 [CLEANUP] Avoid Hungarian notation in `CSSList`
  src/CSSList/CSSList.php
Labels: cleanup

#873 [TASK] Add type declarations for `OutputFormat::indentWith*`
  CHANGELOG.md
  src/OutputFormat.php
Labels: cleanup

#880 [CLEANUP] Add separate `OutputFormat` properties for arrays
  CHANGELOG.md
  src/OutputFormat.php
  src/OutputFormatter.php
  tests/OutputFormatTest.php
  tests/Unit/OutputFormatTest.php
Labels: cleanup, enhancement, deprecation, to-backport

#871 [FEATURE] Add dedicated property accessors for `OutputFormat`
  config/phpstan-baseline.neon
  src/OutputFormat.php
  tests/Unit/OutputFormatTest.php
Labels: enhancement

#883 [CLEANUP] Add separate `OutputFormat` properties for arrays
  CHANGELOG.md
  src/OutputFormat.php
  src/OutputFormatter.php
  tests/OutputFormatTest.php
Labels: cleanup, enhancement, deprecation, backport

#884 [CLEANUP] Add more type assertions in the tests
  config/phpstan-baseline.neon
  tests/ParserTest.php
Labels: cleanup

#886 [TASK] Make all non-private properties `@internal`
  CHANGELOG.md
  src/CSSList/CSSList.php
  src/Comment/Comment.php
  src/OutputFormat.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/RuleSet.php
  src/Settings.php
  src/Value/CSSFunction.php
  src/Value/Value.php
  src/Value/ValueList.php
Labels: to-backport

#889 [TASK] Make all non-private properties `@internal`
  CHANGELOG.md
  src/CSSList/CSSList.php
  src/Comment/Comment.php
  src/OutputFormat.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/RuleSet.php
  src/Settings.php
  src/Value/CSSFunction.php
  src/Value/Value.php
  src/Value/ValueList.php
Labels: backport

#891 [TASK] Use native type declarations for `Renderable`
  CHANGELOG.md
  src/CSSList/AtRuleBlockList.php
  src/CSSList/CSSBlockList.php
  src/CSSList/CSSList.php
  src/CSSList/Document.php
  src/CSSList/KeyFrame.php
  src/Comment/Comment.php
  src/Parser.php
  src/Parsing/OutputException.php
  src/Parsing/ParserState.php
  src/Parsing/SourceException.php
  src/Parsing/UnexpectedTokenException.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Renderable.php
  src/Rule/Rule.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/CalcRuleValueList.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/PrimitiveValue.php
  src/Value/RuleValueList.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/Value.php
  src/Value/ValueList.php
Labels: cleanup

#892 [BUGFIX] Fix return type annotation of `Value::isSize()`
  src/Value/Size.php
Labels: bug, cleanup

#897 [BUGFIX] Add missing imports for `@throws` annotations
  config/phpstan-baseline.neon
  src/Value/CSSFunction.php
Labels: bug, cleanup, to-backport

#899 [CLEANUP] Autoformat the code and organize the imports
  src/Value/Color.php
  src/Value/Value.php
  tests/ParserTest.php
  tests/Unit/Rule/RuleTest.php
Labels: cleanup

#900 [BUGFIX] Add missing imports for `@throws` annotations
  src/Value/CSSFunction.php
Labels: bug, backport

#901 [TASK] Mark `OutputFormat::nextLevel()` as `@internal`
  CHANGELOG.md
  src/OutputFormat.php
Labels: to-backport

#903 [BUGFIX] Fix a type annotation in a test
  tests/Unit/Value/ValueTest.php
Labels: bug, cleanup

#902 [BUGFIX] Fix an incorrect type annotation in `OutputFormat`
  src/OutputFormat.php
Labels: bug, to-backport

#904 [BUGFIX] Fix the parameter name in a type annotation
  config/phpstan-baseline.neon
  src/Property/Charset.php
Labels: bug, cleanup

#905 [TASK] Mark `OutputFormat::nextLevel()` as `@internal`
  CHANGELOG.md
  src/OutputFormat.php
Labels: backport

#906 [BUGFIX] Fix an incorrect type annotation in `OutputFormat`
  src/OutputFormat.php
Labels: bug, cleanup, backport

#910 [CLEANUP] Avoid Hungarian notation for `outputFormat`
  src/CSSList/AtRuleBlockList.php
  src/CSSList/CSSList.php
  src/CSSList/Document.php
  src/CSSList/KeyFrame.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Renderable.php
  src/Rule/Rule.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/CalcRuleValueList.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/ValueList.php
Labels: cleanup

#913 [TASK] Mark many parsing-related methods as `@internal`
  CHANGELOG.md
  src/CSSList/CSSList.php
  src/CSSList/Document.php
  src/Parsing/ParserState.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/CalcFunction.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/Value.php
Labels: backport

#912 [TASK] Move some tests for `Comment` to functional tests
  tests/Functional/.gitkeep
  tests/Functional/Comment/CommentTest.php
  tests/Unit/Comment/CommentTest.php
Labels: cleanup

#915 [TASK] Make the tests more strict
  config/phpstan-baseline.neon
  tests/ParserTest.php
Labels: cleanup

#918 [CLEANUP] Avoid Hungarian notation for `element`
  src/CSSList/Document.php
Labels: cleanup

#917 [CLEANUP] Avoid Hungarian notation for `component`
  src/CSSList/CSSBlockList.php
  src/Value/ValueList.php
Labels: cleanup

#916 [CLEANUP] Avoid Hungarian notation for `arguments`
  src/CSSList/AtRuleBlockList.php
  src/RuleSet/AtRuleSet.php
Labels: cleanup

#920 [DOCS] Fix PR ID in the changelog
  CHANGELOG.md
Labels: documentation

#924 [CLEANUP] Avoid Hungarian notation for `result`
  src/CSSList/AtRuleBlockList.php
  src/CSSList/Document.php
  src/CSSList/KeyFrame.php
  src/OutputFormatter.php
  src/Parsing/ParserState.php
  src/Property/CSSNamespace.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSString.php
  src/Value/Value.php
Labels: cleanup

#926 [CLEANUP] Avoid Hungarian notation for `prefix`
  src/CSSList/CSSList.php
  src/OutputFormat.php
  src/Property/CSSNamespace.php
Labels: cleanup

#927 [TASK] Move some `AtRulBlockList` tests to unit tests
  tests/CSSList/AtRuleBlockListTest.php
  tests/Unit/CSSList/AtRuleBlockListTest.php
Labels: cleanup

#930 [TASK] Use type-safe setters in `OutputFormat` factory methods
  src/OutputFormat.php
  tests/Unit/OutputFormatTest.php
Labels: cleanup

#932 [TASK] Drop redundant constructor code
  src/CSSList/CSSBlockList.php
  src/CSSList/CSSList.php
  src/CSSList/Document.php
  src/CSSList/KeyFrame.php
  src/OutputFormat.php
  src/Parsing/ParserState.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/PrimitiveValue.php
Labels: cleanup

#929 [CLEANUP] Avoid Hungarian notation in `Document`
  src/CSSList/Document.php
Labels: cleanup

#925 [TASK] Drop redundant `OutputException` constructor
  src/Parsing/OutputException.php
Labels: cleanup

#935 [CLEANUP] Avoid Hungarian notation for `position`
  src/Parsing/Anchor.php
  src/Parsing/ParserState.php
  src/RuleSet/RuleSet.php
Labels: cleanup

#942 [CLEANUP] Avoid Hungarian notation for `outputFormat(ter)`
  src/OutputFormat.php
  src/OutputFormatter.php
Labels: cleanup

#940 [CLEANUP] Avoid Hungarian notation for `text`/`characters`
  src/Parser.php
  src/Parsing/ParserState.php
Labels: cleanup

#947 [CLEANUP] Avoid Hungarian notation for `currentPosition`
  src/Parsing/ParserState.php
Labels: cleanup

#948 [CLEANUP] Avoid Hungarian notation for `charset`
  src/Parsing/ParserState.php
  src/Property/Charset.php
Labels: cleanup

#951 [CLEANUP] Drop redundant `@internal` annotations
  src/Parsing/ParserState.php
Labels: cleanup

#955 [CLEANUP] Avoid Hungarian notation for `ignoreCase`
  src/Parsing/ParserState.php
  src/Value/CSSFunction.php
  src/Value/CalcFunction.php
  src/Value/Value.php
Labels: cleanup

#962 [CLEANUP] Ensure `ParserState::strsplit()` always returns array
  src/Parsing/ParserState.php
Labels: cleanup

#959 [CLEANUP] Avoid Hungarian notation for `character`
  src/Parsing/ParserState.php
Labels: cleanup

#960 [CLEANUP] Avoid Hungarian notation for `offset`
  src/Parsing/ParserState.php
Labels: cleanup

#961 [CLEANUP] Avoid Hungarian notation for `isForIdentifier`
  src/Parsing/ParserState.php
Labels: cleanup

#966 [CLEANUP] Use accessors in `OutputFormatter`
  src/OutputFormatter.php
Labels: cleanup

#956 [TASK] Add Tests for `Document::getAllDeclarationBlocks()`
  src/CSSList/Document.php
  tests/Unit/CSSList/DocumentTest.php
Labels: testing

#968 [CLEANUP] Avoid Hungarian notation for `comment(able)`
  src/OutputFormatter.php
  src/Parsing/ParserState.php
Labels: cleanup

#954 [CLEANUP] Don't store array length as a property
  src/Parsing/ParserState.php
Labels: cleanup

#970 [CLEANUP] Avoid Hungarian notation for `caseInsensitive`
  src/Parsing/ParserState.php
Labels: cleanup

#977 [CLEANUP] Avoid Hungarian notation for `start(Position)`
  src/Parsing/ParserState.php
  src/Value/Value.php
Labels: cleanup

#978 [CLEANUP] Add some comments for grouping tests
  tests/Unit/CSSList/AtRuleBlockListTest.php
  tests/Unit/CSSList/DocumentTest.php
  tests/Unit/CSSList/KeyFrameTest.php
Labels: cleanup

#981 [CLEANUP] Avoid Hungarian notation in the exception classes
  src/Parsing/SourceException.php
  src/Parsing/UnexpectedTokenException.php
Labels: cleanup

#980 [CLEANUP] Avoid Hungarian notation in `ParserState`
  src/Parsing/ParserState.php
Labels: cleanup

#982 [CLEANUP] Avoid Hungarian notation in `Charset`
  src/Property/Charset.php
Labels: cleanup

#983 [TASK] Drop unnecessary properties from `UnexpectedTokenException`
  src/Parsing/UnexpectedTokenException.php
Labels: cleanup

#988 [CLEANUP] Use `null` for unset value in `DeclarationBlock::parse()`
  config/phpstan-baseline.neon
  src/RuleSet/DeclarationBlock.php
Labels: cleanup

#989 [CLEANUP] Avoid Hungarian notation in `Selector`
  src/Property/Selector.php
Labels: cleanup

#973 [CLEANUP] Drop some comments from testcases
  tests/Unit/CSSList/AtRuleBlockListTest.php
  tests/Unit/CSSList/DocumentTest.php
  tests/Unit/CSSList/KeyFrameTest.php
Labels: cleanup

#992 [CLEANUP] Avoid Hungarian notation in `Rule`
  src/Rule/Rule.php
Labels: cleanup

#997 [CLEANUP] Avoid Hungarian notation in `AtRuleSet`
  src/RuleSet/AtRuleSet.php
Labels: cleanup

#1008 [CLEANUP] Avoid Hungarian notation in `Settings`
  src/CSSList/CSSList.php
  src/Parsing/ParserState.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Settings.php
  src/Value/LineName.php
  src/Value/Value.php
  tests/Unit/SettingsTest.php
Labels: cleanup

#1006 [TASK] Deprecate `__toString()`
  CHANGELOG.md
  src/CSSList/AtRuleBlockList.php
  src/CSSList/CSSList.php
  src/CSSList/KeyFrame.php
  src/Comment/Comment.php
  src/OutputFormatter.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Property/Selector.php
  src/Renderable.php
  src/Rule/Rule.php
  src/RuleSet/AtRuleSet.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/Color.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/ValueList.php
  tests/Functional/Comment/CommentTest.php
  tests/FunctionalDeprecated/.gitkeep
  tests/FunctionalDeprecated/Comment/CommentTest.php
Labels: to-backport

#990 [CLEANUP] Refactor `::getAllDeclarationBlocks()`
  src/CSSList/CSSBlockList.php
Labels: cleanup

#1013 [FEATURE] Add internal getters to `Settings` and use them
  src/CSSList/CSSList.php
  src/Parsing/ParserState.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Settings.php
  src/Value/LineName.php
  src/Value/Value.php
  tests/Unit/SettingsTest.php
Labels: cleanup, enhancement

#1018 [TASK] Deprecate greedy calculation of selector specificity
  CHANGELOG.md
  src/Property/Selector.php
Labels: to-backport

#1022 [TASK] Deprecate greedy calculation of selector specificity
  CHANGELOG.md
  src/Property/Selector.php
Labels: backport

#1024 [CLEANUP] Avoid Hungarian notation for `rules`
  src/RuleSet/RuleSet.php
Labels: cleanup

#1029 [CLEANUP] Avoid Hungarian notation for `nextLevelFormat`
  src/OutputFormat.php
  src/RuleSet/RuleSet.php
Labels: cleanup

#1030 [CLEANUP] Avoid Hungarian notation for `searchPattern`
  src/RuleSet/RuleSet.php
Labels: cleanup

#1031 [CLEANUP] Avoid Hungarian notation for `sibling`
  src/RuleSet/RuleSet.php
Labels: cleanup

#1033 [CLEANUP] Avoid Hungarian notation for `consumedText`
  src/RuleSet/RuleSet.php
Labels: cleanup

#1034 [CLEANUP] Improve a parameter name in `RuleSet::addRule()`
  src/RuleSet/RuleSet.php
Labels: cleanup

#1037 [TASK] Mark `Selector::isValid()` as `@internal`
  CHANGELOG.md
  src/Property/Selector.php
Labels: to-backport
