Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2025-06, with the labels that each got.

#1265 [BUGFIX] Set line number for `addRule()` with only column number
  CHANGELOG.md
  src/RuleSet/RuleSet.php
  tests/Unit/RuleSet/RuleSetTest.php
Labels: bug, to-backport

#1266 [TASK] Add tests for `addRule()` with a sibling
  tests/Unit/RuleSet/RuleSetTest.php
Labels: testing, to-backport

#1272 [CLEANUP] Extract method `RuleSet::comparePositionable`
  src/RuleSet/RuleSet.php
Labels: cleanup

#1274 [CLEANUP] Separate some test methods in `RuleSetTest`
  tests/Unit/RuleSet/RuleSetTest.php
Labels: cleanup, testing

#1279 [TASK] Add unit tests for `RuleSet::getRulesAssoc`
  tests/Unit/RuleSet/RuleSetTest.php
Labels: testing

#1284 [TASK] Update `RuleSet::addRule` to use `getLineNumber`
  src/RuleSet/RuleSet.php
Labels: cleanup, deprecation, refactor

#1286 [TASK] Add tests for `getLineNumber`
  tests/Unit/CSSList/AtRuleBlockListTest.php
  tests/Unit/CSSList/CSSListTest.php
  tests/Unit/CSSList/KeyFrameTest.php
  tests/Unit/Comment/CommentTest.php
  tests/Unit/Parsing/OutputExceptionTest.php
  tests/Unit/Parsing/SourceExceptionTest.php
  tests/Unit/Parsing/UnexpectedEOFExceptionTest.php
  tests/Unit/Parsing/UnexpectedTokenExceptionTest.php
  tests/Unit/Value/CSSStringTest.php
  tests/Unit/Value/CalcRuleValueListTest.php
  tests/Unit/Value/URLTest.php
Labels: testing

#1287 [TASK] Remove `getColNo()`
  CHANGELOG.md
  src/Position/Position.php
  src/Position/Positionable.php
  tests/UnitDeprecated/Position/PositionTest.php
Labels: removal

#1290 [BUGFIX] Exclude absent line number from exception message
  src/Parsing/SourceException.php
  tests/Unit/Parsing/SourceExceptionTest.php
Labels: bug

#1291 [TASK] Add `RuleContainerTest` trait, use in `RuleSetTest`
  tests/Unit/RuleSet/RuleContainerTest.php
  tests/Unit/RuleSet/RuleSetTest.php
Labels: testing, refactor

#1293 [BUGFIX] Allow comma in selectors
  CHANGELOG.md
  src/Property/Selector.php
  tests/Unit/Property/SelectorTest.php
Labels: bug, to-backport

#1296 [BUGFIX] Correct an exception message
  src/RuleSet/DeclarationBlock.php
Labels: bug

#1300 [CLEANUP] Avoid spaces before colons in the Mermaid code
  README.md
Labels: documentation, cleanup, developer-specific

#1299 [CLEANUP] Order class names in the class diagram alphabetically
  README.md
Labels: documentation, cleanup, developer-specific
