Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2025-01, with the labels that each got.

#788 [TASK] Add a section on creating PRs to `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#790 [BUGFIX] Parse @font-face src property as comma-delimited list
  CHANGELOG.md
  src/Rule/Rule.php
  tests/Unit/.gitkeep
  tests/Unit/Rule/RuleTest.php
Labels: bug, to-backport

#792 [CLEANUP] Remove trailing space from changelog
  CHANGELOG.md
Labels: documentation, cleanup

#793 [TASK] Add TestCase for `Value\Color`
  tests/Unit/Value/ColorTest.php
Labels: css3, testing

#795 [BUGFIX] Add missing import for a type annotation in a test
  tests/Unit/Rule/RuleTest.php
Labels: bug

#796 [TASK] Update the development tools
  .github/workflows/ci.yml
  .phive/phars.xml
  composer.json
Labels: dependencies

#794 [BUGFIX] Parse `@font-face` src property as comma-delimited list
  CHANGELOG.md
  src/Rule/Rule.php
  tests/Unit/Rule/RuleTest.php
Labels: bug, backport

#797 [FEATURE] Support rgba and rgb (etc.) being aliases
  CHANGELOG.md
  src/Value/Color.php
  tests/Unit/Value/ColorTest.php
Labels: enhancement, css4

#800 [FEATURE] Parse color functions with modern syntax
  CHANGELOG.md
  src/Value/Color.php
  tests/Unit/Value/ColorTest.php
Labels: enhancement, css4

#802 [CLEANUP] Avoid Hungarian notation in `Color` class
  src/Value/Color.php
Labels: cleanup

#803 [BUGFIX] Don't render `rgb` colors with `%` values as hex
  CHANGELOG.md
  src/Value/Color.php
  tests/Unit/Value/ColorTest.php
Labels: bug, css4

#787 [TASK] Update PHPStan and Rector
  composer.json
Labels: dependencies

#804 [CLEANUP] Avoid Hungarian notion for the `Commentable` interface
  src/CSSList/CSSList.php
  src/Comment/Commentable.php
  src/Property/CSSNamespace.php
  src/Property/Charset.php
  src/Property/Import.php
  src/Rule/Rule.php
  src/RuleSet/RuleSet.php
Labels: cleanup

#805 [TASK] Use native `void` return type declarations
  CHANGELOG.md
  src/CSSList/CSSBlockList.php
  src/Comment/Commentable.php
  src/Property/Charset.php
  src/Property/Selector.php
  src/Rule/Rule.php
Labels: cleanup

#807 [DOCS] Remove section on testing from `README.md`
  README.md
Labels: documentation, developer-specific

#810 [TASK] Move `SettingsTest` to the unit tests
  tests/Unit/SettingsTest.php
Labels: cleanup

#812 [CLEANUP] Avoid Hungarian notation in `AtRuleBlockList`
  src/CSSList/AtRuleBlockList.php
Labels: cleanup

#816 [TASK] Add a release checklist
  docs/release-checklist.md
Labels: documentation, developer-specific

#817 [TASK] Avoid Hungarian notation in `CSSBlockList`
  src/CSSList/CSSBlockList.php
Labels: cleanup

#823 [CLEANUP] Autoformat the changelog
  CHANGELOG.md
Labels: documentation, cleanup

#824 [CLEANUP] Use spaces for indenting the fixture CSS files
  tests/fixtures/-fault-tolerance.css
  tests/fixtures/1readme.css
  tests/fixtures/2readme.css
  tests/fixtures/atrules.css
  tests/fixtures/calc.css
  tests/fixtures/case-insensitivity.css
  tests/fixtures/colortest.css
  tests/fixtures/escaped-tokens.css
  tests/fixtures/ie.css
  tests/fixtures/inner-color.css
  tests/fixtures/missing-property-value.css
  tests/fixtures/namespaces.css
  tests/fixtures/nested.css
  tests/fixtures/slashed.css
  tests/fixtures/specificity.css
  tests/fixtures/url.css
  tests/fixtures/values.css
  tests/fixtures/whitespace.css
Labels: cleanup

#820 [TASK] Avoid using `@covers` annotations referencing methods
  config/phpstan-baseline.neon
  tests/ParserTest.php
  tests/RuleSet/LenientParsingTest.php
Labels: cleanup

#814 [BUGFIX] Create default `Size` with correct types in `expandBackgroundShorthand`
  config/phpstan-baseline.neon
  src/RuleSet/DeclarationBlock.php
Labels: bug, to-backport

#827 [CLEANUP] Add `Color::getRealName` method
  src/Value/Color.php
Labels: cleanup

#825 [CLEANUP] Extract method `Color::renderAsHex`
  src/Value/Color.php
Labels: cleanup

#828 [BUGFIX] Create `Size` with correct types in `expandBackgroundShorthand`
  CHANGELOG.md
  src/RuleSet/DeclarationBlock.php
Labels: bug, backport

#806 [DOCS] Integrate the `8.x` changelog into the `main` changelog
  CHANGELOG.md
Labels: documentation

#834 [CLEANUP] Avoid Hungarian notation for `oParserState`
  src/CSSList/CSSList.php
  src/CSSList/Document.php
  src/Parser.php
  src/Parsing/Anchor.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
  src/Value/CSSFunction.php
  src/Value/CSSString.php
  src/Value/CalcFunction.php
  src/Value/LineName.php
  src/Value/Size.php
  src/Value/URL.php
  src/Value/Value.php
Labels: cleanup

#835 [CLEANUP] Avoid Hungarian notation for `oRule`/`oRuleSet`
  src/CSSList/CSSBlockList.php
  src/Rule/Rule.php
  src/RuleSet/RuleSet.php
Labels: cleanup

#839 [CLEANUP] Drop redundant type annotations in `CSSList\`
  src/CSSList/CSSList.php
  src/CSSList/Document.php
Labels: cleanup

#842 [CLEANUP] Remove redundant type annotations in `Property`
  src/Property/Charset.php
  src/Property/Import.php
Labels: cleanup

#845 [CLEANUP] Drop redundant type annotations in `RuleSet`
  src/RuleSet/RuleSet.php
Labels: cleanup

#846 [CLEANUP] Avoid Hungarian notation for `oSelector`
  src/CSSList/CSSBlockList.php
  src/RuleSet/DeclarationBlock.php
Labels: cleanup

#841 [TASK] Add native type declarations for anonymous functions
  CHANGELOG.md
  src/CSSList/CSSList.php
  src/RuleSet/RuleSet.php
Labels: cleanup

#848 [CLEANUP] Drop a redundant type annotation in `Parser`
  src/Parser.php
Labels: cleanup

#850 [CLEANUP] Avoid Hungarian notation for `aComments`
  src/CSSList/CSSList.php
  src/OutputFormatter.php
  src/Parsing/ParserState.php
  src/Rule/Rule.php
  src/RuleSet/DeclarationBlock.php
Labels: cleanup

#840 [BUGFIX] Render RGB functions with "modern" syntax if required
  CHANGELOG.md
  src/Value/Color.php
  tests/Unit/Value/ColorTest.php
Labels: bug, enhancement, css4

#851 [CLEANUP] Avoid Hungarian notation in `CSSBlockList` (part 2)
  src/CSSList/CSSBlockList.php
Labels: cleanup

#853 [CLEANUP] Extract method `Color::shouldRenderAsHex`
  src/Value/Color.php
Labels: cleanup

#854 [CLEANUP] Avoid Hungarian notation for `aContents` and items
  src/CSSList/CSSBlockList.php
  src/CSSList/CSSList.php
Labels: cleanup

#855 [CLEANUP] Avoid Hungarian notation for `iKey`
  src/CSSList/CSSList.php
  src/RuleSet/DeclarationBlock.php
  src/RuleSet/RuleSet.php
Labels: cleanup

#856 [CLEANUP] Improve readability of `instanceof` calls
  src/Rule/Rule.php
  src/Value/Color.php
  tests/ParserTest.php
Labels: cleanup

#857 [CLEANUP] Avoid Hungarian notation for `oList` and `oListItem`
  src/CSSList/CSSList.php
  src/RuleSet/DeclarationBlock.php
  src/Value/CalcFunction.php
  src/Value/Value.php
Labels: cleanup

#847 [TASK] Add accessor tests for `OutputFormat` (part 1)
  tests/Unit/OutputFormatTest.php
Labels: cleanup, enhancement
