Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2025-07, with the labels that each got.

#1301 [DOCS] Fix class list in class diagram
  README.md
Labels: documentation

#1302 [DOCS] Make the class diagram markers generator-friendly
  README.md
Labels: documentation

#1304 [DOCS] Change some arrow types in the class diagram
  README.md
Labels: documentation

#1307 [DOCS] Temporarily drop some markers from the class diagram
  README.md
Labels: documentation

#1311 [DOCS] Reorder some lines in the class diagram (part 5)
  README.md
Labels: documentation

#1313 [DOCS] Reorder some lines in the class diagram (part 7)
  README.md
Labels: documentation

#1314 [DOCS] Reorder some lines in the class diagram (part 8)
  README.md
Labels: documentation

#1316 [DOCS] Reorder some lines in the class diagram (part 10)
  README.md
Labels: documentation

#1318 [DOCS] Reorder some lines in the class diagram (part 12)
  README.md
Labels: documentation

#1329 [DOCS] Integrate the 8.9.0 changelog into main changelog
  CHANGELOG.md
Labels: documentation

#1333 [CLEANUP] Remove superfluous Rector rule
  config/rector.php
Labels: cleanup, developer-specific

#1337 [CLEANUP] Remove impossible conditional
  config/phpstan-baseline.neon
  src/CSSList/CSSList.php
Labels: cleanup

#1343 [CLEANUP] Update `RuleSet` DocBlock
  src/RuleSet/RuleSet.php
Labels: cleanup

#1344 [CLEANUP] Reorder `use`s in `DeclarationBlockTest`
  tests/Unit/RuleSet/DeclarationBlockTest.php
Labels: cleanup

#1351 [TASK] Test `RuleSet` constructor with `null` explicitly passed
  tests/Unit/RuleSet/RuleSetTest.php
Labels: testing

#1354 [DOCS] Correct `}` to `)` in changelog
  CHANGELOG.md
Labels: documentation, bug

#1358 [CLEANUP] Ignore warnings for explicitly invalid values in tests
  config/phpstan-baseline.neon
  tests/Unit/Parsing/UnexpectedEOFExceptionTest.php
  tests/Unit/Parsing/UnexpectedTokenExceptionTest.php
Labels: cleanup
