Repository MyIntervals/PHP-CSS-Parser, pull requests merged in 2025-08, with the labels that each got.

#1367 [BUGFIX] Use the safe `file_get_contents` in `quickdump.php`
  bin/quickdump.php
Labels: bug, cleanup

#1368 [BUGFIX] Use the safe regexp functions in `CSSList`
  CHANGELOG.md
  src/CSSList/CSSList.php
Labels: bug, cleanup

#1369 [CLEANUP] Avoid Hungarian notation in `quickdump.php`
  bin/quickdump.php
Labels: cleanup

#1372 [BUGFIX] Improve selector validation performance
  CHANGELOG.md
  src/Property/KeyframeSelector.php
  src/Property/Selector.php
Labels: bug, cleanup, optimization
